### ISSUE TITLE
RPMs include /usr/share/gems/* conflicting with rubygems official package

### ISSUE THREAD

**Issue by Madko** [OpenNebula/addon-installgems#4]
Hi,

I don't know well fpm so maybe this problem is not on your side. The resulting packages from the addon-installgems seems to have in the %files section of their spec file some directories that should not be listed because they are provided by others package. So when you try to install them, rpm prevent this because of this conflicting files/directories.

ex with rubygem-nokogiri:
$ rpm -qpl rubygem-nokogiri-1.6.6.2-1.x86_64.rpm
...
/usr/share/gems/doc
...
$  rpm -qf /usr/share/gems/doc
rubygems-2.0.14-22.el7_0.noarch

All this rubygem-* also inter-conflict since they all say that they provide /usr/share/gem/doc

I think these RPMs should include /usr/share/gems/doc/NAME-VERSION instead /usr/share/gems/doc

Best regards,

Edouard

**Comment by alvarosimon** [comment]
Hi
In our case we didn't get the error message installing these rpms but you are right /usr/share/gems/doc is already generated by rubygems package. As you said this dep is included by fpm automatically because this directory is always generated when you install new gems locally but we can modify the fpm command to exclude it. We will change it asap to avoid these warnings.

Cheers and thanks
Alvaro

**Comment by alvarosimon** [comment]
Fixed via #5 
@Madko can you test if it also works in your side?

Cheers
Alvaro

**Comment by Madko** [comment]
Hi Alvaro,

this fix seems to work, at least no more doc directory in the RPM:
$ rpm -qpl gems_dir/rubygem-nokogiri-1.6.6.2-1.x86_64.rpm |grep doc
nothing.

I will try to install them soon.

**Comment by alvarosimon** [comment]
@Madko have you tried the new rpms generated with the script? let us know if you find another issue

**Comment by alvarosimon** [comment]
This issue was already fixed
