### ISSUE TITLE
Problem with rpm rubygem-nokogiri generated with gem_packages.py

### ISSUE THREAD

**Issue by StephaneGerardVUB** [OpenNebula/addon-installgems#6]
Hi Alvaro,
I'm trying to install an OpenNebula frontend with Quattor, and to avoid the /usr/share/one/install_gems step (it can't be done unattended, unless you modify the script...), I've generated with your script the needed rpm's for some rubygems. These got installed fine, but during the start of service opennebula-sunstone, I get the following error message :
/usr/lib/one/ruby/opennebula/xml_utils.rb:140: nokogiri gem not installed. (RuntimeError)
while the package rubygem-nokogiri is well installed. And when I do "gem list", I don't see nokogiri in the list of local gems.
Cheers,
Stéphane

**Comment by alvarosimon** [comment]
Hi Stéphane

Could you give us more info about which OS are you using?, and the output of these commands:
`# rpm -qa|grep rubygem`
and
`# gem list`

Cheers
Alvaro

**Comment by StephaneGerardVUB** [comment]
Hi Alvaro,
OS :
Scientific Linux release 6.6 (Carbon)
RPMs :
[root@vscvhost01 ~]# rpm -qa | grep rubygem
rubygem-multipart-post-2.0.0-1.noarch
rubygem-polyglot-0.3.5-1.noarch
rubygems-1.3.7-5.el6.noarch
rubygem-sinatra-1.0-2.el6.noarch
rubygem-inflection-1.0.0-1.noarch
rubygem-zendesk_api-1.4.6-1.noarch
rubygem-rack-protection-1.5.3-1.noarch
rubygem-mini_portile-0.6.2-1.noarch
rubygem-trollop-2.1.2-1.noarch
rubygem-parse-cron-0.1.4-1.noarch
rubygem-sqlite3-1.3.10-1.x86_64
rubygem-nokogiri-1.5.11-1.x86_64
rubygem-json-1.8.2-1.x86_64
rubygem-faraday-0.9.1-1.noarch
rubygem-multi_json-1.11.0-1.noarch
rubygem-rack-1.1.0-2.el6.noarch
rubygem-rack-test-0.5.4-1.el6.noarch
rubygem-hashie-3.4.1-1.noarch
rubygem-sequel-4.21.0-1.noarch
rubygem-thin-1.6.3-1.x86_64
rubygem-aws-sdk-1.40.3-1.el6.noarch
rubygem-builder-3.2.2-1.noarch
rubygem-tilt-2.0.1-1.noarch
rubygem-curb-0.8.8-1.x86_64
rubygem-uuidtools-2.1.5-1.noarch
rubygem-daemons-1.2.2-1.noarch
rubygem-sqlite3-ruby-1.2.4-5.el6.x86_64
rubygem-mime-types-1.25.1-1.noarch
rubygem-xml-simple-1.1.5-1.noarch
rubygem-eventmachine-1.0.7-1.x86_64
rubygem-amazon-ec2-0.9.17-1.noarch
rubygem-treetop-1.6.2-1.noarch
rubygem-net-ldap-0.8.0-1.noarch
rubygem-mysql-2.9.1-1.x86_64
rubygem-ox-2.1.8-1.x86_64
GEM LIST :
[root@vscvhost01 ~]# gem list

*** LOCAL GEMS ***

aws-sdk (1.40.3)
rack (1.1.0)
rack-test (0.5.4)
sinatra (1.0)
sqlite3-ruby (1.2.4)
Cheers,
St.

**Comment by alvarosimon** [comment]
Hi Stéphane

Thanks a lot for the info!. We have tested this script with Centos7 and debian7 so probably there is some issue with Centos/SL6. I will try this in a VM to reproduce your issue asap, it seems that the packages are installed in SL6 but the gems are not visible from ruby. I will keep you informed.

Cheers
Alvaro

**Comment by alvarosimon** [comment]
Hi Stéphane

I'm able to reproduce the issue in SL6, that's good :-). The problem is the prefix path that is hardcoded for the redhat OS favours and it seems that SL6 and SL7 versions use a different gem path so that's the reason why after the rpm installation ruby is not able to see the new gems. I will fix this asap, I hope to update the script tomorrow to change the prefix path depending on the OS version. 

Meanwhile if you want to try you can change the script to use the correct path for SL6, you only have to change the line **130** by the correct path:

`         prefix = "/usr/lib/ruby/gems/1.8"`

and run the script again as oneadmin:
`./gem_packages.py -p`

you must remove all rubygem* installed gems and install opennebula packages again and the new rubygem*.rpm, after that you can check the list of gems, you should see the complete list. This is just a workaround we hope to provide the fix tomorrow  :smile: 

Cheers
Alvaro

**Comment by alvarosimon** [comment]
Hi Stéphane

The script was updated with the new fix, could you try the new script? let me know if something is going wrong. It's working in my testbed using Centos6.6,  you should  reinstall the rubygem packages.

Cheers
Alvaro

**Comment by StephaneGerardVUB** [comment]
Hi Alvaro,
It works.
Thanks !
Stéphane

**Comment by alvarosimon** [comment]
Perfect! about OpenNebula configuration there are some `template-library-examples` for Quattor, we have submitted a new PR to include some OpenNebula examples, you can find it here: 

https://github.com/quattor/template-library-examples/pull/23

maybe it could be useful
Cheers
Alvaro
